version: "3.9"

services:
  expense-tracker:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./templates:/app/templates
      - ./static:/app/static
    env_file:
      - .env



